### ISSUE TITLE
Fix saving

### ISSUE THREAD

**Issue by adityab** [adityab/Awwation#4]
Client-side saving does not work in Firefox, Opera, or IE at the moment.

**Comment by codedread** [comment]
Is there any way you can open a new tab with the SVG+JS embedded so people can preview their work?

**Comment by adityab** [comment]
I've tried it, see this [commit](https://github.com/adityab/Awwation/commit/1eca47bba02396e78f937d09ef8daa9e1f786ecf) - but:  
**Chrome**: Presentation opens in a new tab and plays fine, but the `Save As...` menu item is greyed out.
**Firefox**: Presentation opens in a new tab, but the JavaScript cannot be executed.

I might have missed another way though, if you have any ideas, let me know!

**Comment by adityab** [comment]
Fixed this by using Downloadify, a tiny flash solution. Not ideal, but the only way for now. Saving works on all major browsers.
